pipeline: Kandinskiy2_2 

common:
  prompt: Professional high-quality wide-angle digital art of an iron man in helmet. photorealistic, epic fantasy, dramatic lighting, cinematic, extremely high detail, cinematic lighting, trending on artstation, cgsociety, realistic rendering of Unreal Engine 5, 8k, 4k, HQ, wallpaper
  negative_prompt: lowres, worst quality, low quality
  seed: 17
  img_h: 768 
  img_w: 768 
  num_inference_steps: 50
  controlnet_strength: 0.5
  prior_prompt_strength: 0.85
  negative_prompt_prior_strength: 1.0
  prior_name: kandinsky-community/kandinsky-2-2-prior
  model_name: kandinsky-community/kandinsky-2-2-controlnet-depth
  original_output_size: true 
  controlnet_processor: depth  
  hist_normalize: lab
  input_video_path: ./video/input/man.mp4
  output_video_path: ./video/output/kandinskiy2_2.mp4

prior_config:
  interpolation_scheduler: ema
  ema: 0.0 
  eta: 0.0
  start_step: 0
  end_step: 50
  const_steps: 0

pipe_config:
  interpolation_scheduler: ema
  ema: 0.0 
  eta: 0.0
  start_step: 0
  end_step: 50
  const_steps: 0

unet_config:
  interpolation_scheduler: cos
  ema: 0.8
  eta: 0.0
  start_step: 0
  end_step: 50
  const_steps: 0
  use_interpolation:
    key: false
    query: false
    value: false
    attention_probs: false
    out_linear: false
  attention_res: 32
  allow_names:
  - down
  - mid
  - up
